### ISSUE TITLE
Add 🔥smoke alarm automations

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#39]
With [Nest Protect integration](https://github.com/iMicknl/ha-nest-protect) available (thanks @iMicknl ) I can start automating certain fire related conditions.

### Goals
- [x] Turn off ♨boiler (exists if you have a Nest thermostat).
- [ ] Visual notifications using lights (exists if you have Lifx).
- [x] [Harmful sensor alerts](https://github.com/dannytsang/homeassistant-config/commit/3845fe4aa158f6c1301c9fb98893003dfd3d5968)
- ~~[ ] [Use presence detection to see if anyone is home](https://github.com/dannytsang/homeassistant-config/issues/39#issuecomment-1074514509).~~

**Comment by jcallaghan** [comment]
I will follow with interest! I think we are both heading down the same path > https://github.com/jcallaghan/home-assistant-config/issues/225

**Comment by dannytsang** [comment]
The motion sensor seems quite unreliable. It updates anywhere between every minute to 10 minutes. An example below from the smoke alarm above the stairs where people tend not to hang around at.

I am excluding these from the existing motion sensors for now because having the stairs light on for 10+ minutes at night is not very convient.

![image](https://user-images.githubusercontent.com/567982/159375299-1120d674-dd3c-41b6-a064-26995f60b2f2.png)

**Comment by iMicknl** [comment]
@dannytsang this is a known limitation unfortunately; https://github.com/iMicknl/ha-nest-protect#known-limitations. That is the reason why I use my Nest Protect occupancy sensors only to see if someone entered my hallway / entrance.

**Comment by dannytsang** [comment]
> @dannytsang this is a known limitation unfortunately; https://github.com/iMicknl/ha-nest-protect#known-limitations. That is the reason why I use my Nest Protect occupancy sensors only to see if someone entered my hallway / entrance.

@iMicknl Thanks for pointing that out. I have re-adjusted my groups accordingly and still a great integration.
